### PR TITLE
Add lecture on Web Browsers

### PR DESCRIPTION
**Pull request by rubensworks**
This PR adds a a new lecture that focuses on the _history_ and _internals_ of moderns web browsers.

I did not link to the lecture yet from the table of contents, as we should probably first discuss what the new outline will become.

Any feedback is welcome! :-)

I hope to start recording videos next week or the week after, so initially having only feedback on the initial parts is fine as well, so I can record those first.

### CODE REVIEW

**Comment by rubensworks** [comment]
For reference, introduction and history have now been recorded. (37 minutes in total so far)

**Comment by Dexagod** [comment]
Might want to make sure text is not pushed to the bottom of the slide. Multiple slides have text that nearly touch the bottom of the slide. I think a simple CSS fix to lessen the space between points could solve most of the problems.

**Comment by RubenVerborgh** [comment]
Yeah, but don't break my grid 😅
Sometimes it's a matter of copyfitting.

There might also be a couple of CSS classes such as `.long` (if I remember) that have more compressed versions indeed.

**Comment by RubenVerborgh** [comment]
Off to a good start of the 2024 edition!

**Pull request merged**
