### PR TITLE
Print stylesheet

### PR DESCRIPTION
**Pull request by Dromin**
Added a stylesheet for media="print" to allow printing the presentations from the browser.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Hi @Dromin, thanks for this pull request.

Is printing currently broken for you?
Printing should work in outline mode (not yet in full-screen); the CSS for that is part of the template.

Would this stylesheet also make it work when full screen is enabled?

**Comment by Dromin** [comment]
I must confess I didn't think to test it in outline mode. I just took a look, and it does work, but I think there are a few issues:
- No border around the slides, making the slides harder to separate visually
- Slides can be 'split' in two when a page break occurs in the middle of a slide

My stylesheet would make it work in fullscreen mode and also adds borders and prevents page breaks in the middle of a slide.

**Comment by Dromin** [comment]
Note: I just tested it in Chrome (I'm a Firefox user) and my stylesheet does change the way the slides are printed in Chrome. Currently they print in landscape mode, one slide per page, while my stylesheet will make it print in portrait mode, two slides per page.

**Comment by RubenVerborgh** [comment]
Thanks for the clarification. I'll need to think a bit about this. There's also value in the "one slide per page" approach, as you can then always fit a different number of slides per page using the printing dialog options. I wonder if we can convince Firefox do behave the same way as Chrome.

The splitting definitely is an issue, so it's good to have this fixed.

I'll probably apply your code directly [to the template](https://github.com/RubenVerborgh/Shower-Clear) in an `@media print` block together with the [existing print code](https://github.com/RubenVerborgh/Shower-Clear/blob/master/styles/_print.scss) (which is borrowed from the Shower template).

**Comment by Dromin** [comment]
> I wonder if we can convince Firefox do behave the same way as Chrome.

I think it can be done by explicitly setting the page to print in landscape mode and forcing a page break after every slide:

```
@media print {

    @page {
        margin: 1.5cm;
        size: landscape;
    }

    .slide {
        border: 1px solid black;
        page-break-inside: avoid;
        page-break-after: always;
    }
}
```

This looks very similar in Firefox and Chrome. I did add a thin border around every slide, because it looks more tidy when multiple slides are printed on one page.

**Comment by Dromin** [comment]
This rule will fix the problem with printing from fullscreen mode:

```
@media print {

    shower.full {
        transform: none !important; /* override inline styles */
    }
}
```

The `position: static !important;` rule was not necessary, because `position: absolute;` was inside an `@media screen {}`block in shower-clear.css, which I failed to notice the first time.

**Comment by RubenVerborgh** [comment]
Follow-up in RubenVerborgh/Shower-Clear#1.

**Pull request closed without merging**
