### PR TITLE
Little typo + clarification

### PR DESCRIPTION
**Pull request by ManuDeBuck**
To me it seemed like a good idea to clarify that JSON-LD also supports the default graph?
Although this is obvious, it caused me a little confusion.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Can indeed be clarified, but the specific suggestion is confusing since N-Quads and TriG support default graphs too.

Maybe another mitigation is to change the row header to "also named graphs"?

**Comment by RubenVerborgh** [comment]
Cfr. https://rubenverborgh.github.io/WebFundamentals/semantic-web/#dataset

> Not all concrete syntaxes support named graphs.
>   All syntaxes support the default graph.

**Comment by ManuDeBuck** [comment]
> Can indeed be clarified, but the specific suggestion is confusing since N-Quads and TriG support default graphs too.
> 
> Maybe another mitigation is to change the row header to "also named graphs"?

Sorry, I did indeed overlook this. Your suggestion is a lot clearer.

**Comment by RubenVerborgh** [comment]
Cherry-picked 9c673e43032f76f36a89189b045bc2195d20b3e3 as 6e818732caa25b30721502d13fc2ace1437a8efe.

**Pull request closed without merging**
