### PR TITLE
Corrected month

### PR DESCRIPTION
**Pull request by yeonsann**
Change the date for the Video in the Web lecture to the correct month: Mar -> May.

### CODE REVIEW

**Comment by yeonsann** [comment]
I'd also like to make you aware that the Video in the Web URL doesn't work for me.

**Comment by RubenVerborgh** [comment]
Thanks!

> I'd also like to make you aware that the Video in the Web URL doesn't work for me.

Weird, I double-checked and it opened for me. It's not a direct link (Ufora doesn't allow), but should ultimately get you there.

**Comment by yeonsann** [comment]
I do get directed to ufora, but it's an empty page:
image

**Comment by RubenVerborgh** [comment]
Oh no… hope these work better: ca25dcada767bc7366f3cace50c8f7f8824238e8

**Comment by yeonsann** [comment]
That does work! Thanks :)

**Pull request merged**
